import { CreateFoodDto } from '../dto/create-food.dto';

export const foodSeeds: CreateFoodDto[] = [
  // 蔬菜類
  {
    name: '白米飯',
    calories: 116,
    protein: 2.6,
    carbohydrates: 25.6,
    fat: 0.3,
    fiber: 0.4,
    servingSize: '100g',
    category: '穀物',
  },
  {
    name: '雞胸肉',
    calories: 165,
    protein: 31,
    carbohydrates: 0,
    fat: 3.6,
    servingSize: '100g',
    category: '肉類',
  },
  {
    name: '鮭魚',
    calories: 208,
    protein: 25,
    carbohydrates: 0,
    fat: 12,
    servingSize: '100g',
    category: '魚類',
  },
  {
    name: '雞蛋',
    calories: 155,
    protein: 13,
    carbohydrates: 1.1,
    fat: 11,
    servingSize: '1顆',
    category: '蛋類',
  },
  {
    name: '牛奶',
    calories: 42,
    protein: 3.4,
    carbohydrates: 5,
    fat: 1,
    servingSize: '100ml',
    category: '乳製品',
  },
  {
    name: '蘋果',
    calories: 52,
    protein: 0.3,
    carbohydrates: 14,
    fat: 0.2,
    fiber: 2.4,
    servingSize: '1顆',
    category: '水果',
  },
  {
    name: '香蕉',
    calories: 89,
    protein: 1.1,
    carbohydrates: 23,
    fat: 0.3,
    fiber: 2.6,
    servingSize: '1根',
    category: '水果',
  },
  {
    name: '菠菜',
    calories: 23,
    protein: 2.9,
    carbohydrates: 3.6,
    fat: 0.4,
    fiber: 2.2,
    servingSize: '100g',
    category: '蔬菜',
  },
  {
    name: '胡蘿蔔',
    calories: 41,
    protein: 0.9,
    carbohydrates: 10,
    fat: 0.2,
    fiber: 2.8,
    servingSize: '100g',
    category: '蔬菜',
  },
  {
    name: '馬鈴薯',
    calories: 77,
    protein: 2,
    carbohydrates: 17,
    fat: 0.1,
    fiber: 2.2,
    servingSize: '100g',
    category: '蔬菜',
  },
];
